config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end
  get 'users/:user_id/posts_list', to: 'api#list_all_user_posts', as: :list_all_user_posts
  get 'users/:user_id/posts/:post_id/comments_list', to: 'api#list_users_and_post_comments', as: :list_users_and_post_comments
  post 'users/:user_id/posts/:post_id/add_comment', to: 'api#add_comment', as: :add_comment
  root 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, class_name: 'Post', foreign_key: 'user_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'user_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'user_id', dependent: :destroy

  validates :name, presence: true
  validates :postsCounter, presence: true, numericality: { greater_than_or_equal_to: 0 }
  after_save :add_token

  def recent_post
    posts.last(3)
  end

  def add_token
    update_column(:authentication_token, ApiHelper::JsonWebToken.encode(email))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all.order('name ASC')
  end

  def show
    return unless User.exists?(params[:id])

    @user = User.find_by(id: params[:id])
    @posts = @user.posts
    @recent_posts = @user.recent_post
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_card.html.erb
<section class='user-section-card'>
<div class="user-img"><img src="<%= user.photo %>" alt="user_photo"></div>

<div class="user-card">
  <div class="user-card__name">
    <%= user.name %>
  </div>
  <div class="user-card__email">
  <p>Number of posts:<%= user.postsCounter || 0 %> </p>  
  </div>
</section>

app/views/users/_users.html.erb
<section class="users">
  <% @users.each do |user| %>
     <%= link_to user do %>
       <%= render partial: "user_card", locals: { user: user } %>
     <% end %>
  <% end %>
</section>

app/views/users/index.html.erb
<%= render 'users' %>

app/views/users/show.html.erb
<section class="user-details">
<section class='user-section-card'>
<div class="user-img"><img src="<%= @user.photo %>" alt="user_photo"></div>
<div class="user-card">
  <div class="user-card__name">
  <h1><%= @user.name %><h1>
  </div>
  <div class="user-card__email">
  <p>Number of posts:<%= @user.postsCounter || 0 %> </p>  
  </div>
</section>


<section class='user-bio'>
<div class="user-card">
  <h1 class="user-card__name">
    Bio
  </h1>
  <p> <%= @user.bio %></p>  
</section>
   
    <% @user.posts.each_with_index do |post,index| %>
      <section class='user-section-card'>
      <div class="user-card comment-card">
        <div class="user-card__name">
         <h3> Post #<%= index+1 %> </h3>
        
        <%= link_to user_post_path(@user.id,post.id),  class: "post-p" do %> 
         <h4><%= post.text %></h4>
        <% end %>
        </div>
        <div class="comment__like">
        <p>Comments:<%= @user.comments.length %> </p>  
        <p>Likes:<%= @user.likes.length %> </p>  
        </div>
      </section>
    <% end %>
 <%= link_to 'See all posts', user_posts_path(@user.id), class: "see-all" %>
 <p class="copy-right">© 2022 GitHub, Inc. Terms</p>
</section>